### PR TITLE
Clicking on the arrow reverses the assets on Swap page (#171)

### PR DESCRIPTION
**Pull request by toniocodo**
* Clicking on the arrow reverses the assets on Swap page

* Change exchange-button into down-up arrow

### CODE REVIEW

**Comment by toniocodo** [comment]
- round button
- background color to `theme.color.background[1]`
- rotate 180deg anim

Video_2022-06-01_150948

**Comment by toniocodo** [comment]
- anim duration to 0.4s

Video_2022-06-01_151644

**Comment by toniocodo** [comment]
strange, it looks good to me on brave

https://user-images.githubusercontent.com/13216617/171597092-6575f187-e891-431d-9575-45201f5bbf6f.mp4

**Comment by dimsome** [comment]
https://user-images.githubusercontent.com/69167058/171597843-d6864f94-755b-4791-994f-d2768f67e775.mp4

This is a better version

**Pull request merged**
