### PR TITLE
208 notify users with legacy earn add withdrawal process

### PR DESCRIPTION
**Pull request by toniocodo**

### CODE REVIEW

**Review by calvinkei — APPROVED** [review]

**Comment by dimsome** [comment]
Screen Shot 2022-09-13 at 23 10 19

For me, it shows like this?

**Comment by toniocodo** [comment]
> Screen Shot 2022-09-13 at 23 10 19
> 
> For me, it shows like this?

I guess you test with impersonator? If yes, you just need a page refresh to update the context after the impersonator login/user update.

**Comment by toniocodo** [comment]
@dimsome I updated the code so you won't have to refresh with impersonator, it will update accordingly

**Comment by dimsome** [comment]
`Legacy Contracts` ?

Does wrap as well, but might give it more space to squeeze it in?

**Comment by dimsome** [comment]
Work mostly fine, a few points:

- For the Withdrawal for vMTA, please replace the balancer logo with MTA, also the MTA amount shows always 0. The function probably to query should change for this one.
- Is there a way to indicate a loading state? otherwise it shows undefined the first few seconds? If it's easy to do, could we add it, if we don't have it yet, then nevermind.
- Could you please also add the new window icon for the button `use V1 withdrawal` and open it in a new window/tab? 
Screen Shot 2022-09-15 at 15 55 12

Also could we use the primary button? or is there is reason we shouldn't?
Screen Shot 2022-09-15 at 15 57 23

**Pull request merged**
