### PR TITLE
Fix hodl time (#218)

### PR DESCRIPTION
**Pull request by dimsome**
bug fix by @biendeveloper

### CODE REVIEW

**Comment by dimsome** [comment]
Screen Shot 2022-10-12 at 18 40 45

Small issue, I have the timeMultiplier of 1.3x, but now it shows 3.0.

@biendeveloper

**Comment by biendeveloper** [comment]
@dimsome Weird, you are trying with this address `0x3df1b295d394b6c77415e9659cc1a7dbcca76be7`? 
With it i got `30 timeMultiplier`  and `30 * 0.1 timeMultiplierSimple` displayed in UI

image

it also tried `dimsome.eth` address and i got `0` timeMultiplier for this `0x8f2326316ec696f6d023e37a9931c2b2c177a3d7` stakedToken
------- 

or do you mean the result should be `1 + 30 * 0.01 %`?

**Comment by dimsome** [comment]
When I try `0x3df1b295d394b6c77415e9659cc1a7dbcca76be7` It also shows 3.00X.

Note we have 2 staked tokens: https://developers.mstable.org/contracts/governance

stkMTA and stkBPT

**Comment by biendeveloper** [comment]
Thanks for explaining @dimsome Fixed it here https://github.com/mstable/mStable-apps/pull/220 we can close this PR

**Comment by dimsome** [comment]
Can you push it to this branch? @biendeveloper

**Comment by biendeveloper** [comment]
@dimsome I don't have access to push to this branch :(

**Comment by dimsome** [comment]
Close #216

**Comment by dimsome** [comment]
OK frontend shows correct multiplier.

@toniocodo @calvinkei , may I merge?

**Review by toniocodo — APPROVED** [review]
LGTM

**Review by calvinkei — APPROVED** [review]

**Pull request merged**
