### PR TITLE
154 icons footer size

### PR DESCRIPTION
**Pull request by toniocodo**
image

### CODE REVIEW

**Comment by dimsome** [comment]
Screen Shot 2022-05-20 at 18 27 33

I feel this one doesn't fit into the style of the others? wdyt?

**Comment by toniocodo** [comment]
yeah, I took the one from mui, maybe I can use a more "square" one, wdyt of this one?
image

**Comment by dimsome** [comment]
I think the others are filled, while this one is outlined, looks like it's a different set.

Also, could we make them smaller, `20px x 20px`?

**Comment by toniocodo** [comment]
image

**Review by dimsome — APPROVED** [review]
I think that looks better! LGTM!

**Pull request merged**
