### PR TITLE
feat: review risk wording

### PR DESCRIPTION
**Pull request by toniocodo**
As per this [notion page](https://www.notion.so/mstable/Website-App-Changes-eb101af537db496b8f6cff3a8e561438) 
- update labels on Save page
- add Risk button
image
- add link to risk page in footer
image

Any comments welcome

### CODE REVIEW

**Comment by dimsome** [comment]
- should keep a sub-headline, otherwise, it looks empty
- should also add an icon for indicating that it opens a new tab

**Comment by camsoulsby** [comment]
Agree with you comments @dimsome. I don't have any great ideas on what the sub-headline should be. I'd suggest that we go ahead with accepting these changes for now, as at least this removes any language that could be seen as potentially misleading. We can always add to it later. These changes were proposed by JS so I can check in with him if you'd rather try to include a subheading now.

**Comment by dimsome** [comment]
@camsoulsby Added a subheadline, wdyt?

- added arrow to Risks button
- 
Screen Shot 2022-06-07 at 14 30 34

**Comment by camsoulsby** [comment]
@dimsome I think that's good. Could also be rephrased as "Powered by DeFi lending markets and the mStable AMM" to avoid using the word "Yeild" twice? Does it maybe need a little more margin below the subheading now that it runs across above the buttons?

**Review by camsoulsby — APPROVED** [review]

**Comment by dimsome** [comment]
@camsoulsby Good points! Adjusted

Screen Shot 2022-06-08 at 11 00 57
.

**Pull request merged**
